import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { BookOpen, Sparkles, CheckCircle2, Loader2, Palette, Users, Tag, AlignLeft } from "lucide-react";
import { useI18n } from "@/components/i18n/i18nProvider";

/**
 * Threshold percentages for magic progress labels.
 * Keys map to magicLabels.step1..step8 in locale files.
 */
const MAGIC_LABEL_STEPS = [
  { at: 5, key: "magicLabels.step1" },
  { at: 10, key: "magicLabels.step2" },
  { at: 20, key: "magicLabels.step3" },
  { at: 35, key: "magicLabels.step4" },
  { at: 50, key: "magicLabels.step5" },
  { at: 70, key: "magicLabels.step6" },
  { at: 85, key: "magicLabels.step7" },
  { at: 95, key: "magicLabels.step8" }
];

function getMagicLabel(percent, t) {
  let activeKey = MAGIC_LABEL_STEPS[0].key;
  for (const entry of MAGIC_LABEL_STEPS) {
    if (percent >= entry.at) {
      activeKey = entry.key;
    }
  }
  return t(activeKey);
}

const SUMMARY_ICONS = {
  topic: Tag,
  title: BookOpen,
  characters: Users,
  style: Palette,
  length: AlignLeft,
};

const SUMMARY_GRADIENTS = {
  topic: "from-amber-400 to-orange-500",
  title: "from-purple-500 to-indigo-600",
  characters: "from-pink-400 to-rose-500",
  style: "from-teal-400 to-cyan-500",
  length: "from-blue-400 to-sky-500",
};

/**
 * SaveStep - Step 4 of the wizard: Final summary and book creation.
 * Visual summary cards + animated creation button + magical progress.
 */
export default function SaveStep({
  bookData,
  selectedCharacters,
  selectedTopic,
  isCreating,
  onCreateBook,
  creationProgress,
  isRTL,
  language
}) {
  const { t } = useI18n();

  const summaryItems = [
    {
      key: "topic",
      label: t("wizard.save.topic"),
      value: selectedTopic || t("wizard.save.notSelected")
    },
    {
      key: "title",
      label: t("wizard.save.storyTitle"),
      value: bookData.title || t("wizard.save.autoGenerated")
    },
    {
      key: "characters",
      label: t("wizard.save.characters"),
      value: selectedCharacters.length > 0
        ? selectedCharacters.map((c) => c.name).join(", ")
        : t("wizard.save.noneSelected")
    },
    {
      key: "style",
      label: t("wizard.save.artStyle"),
      value: bookData.art_style || "disney"
    },
    {
      key: "length",
      label: t("wizard.save.length"),
      value: bookData.length === "short"
        ? t("wizard.preview.lengthShort")
        : bookData.length === "long"
          ? t("wizard.preview.lengthLong")
          : t("wizard.preview.lengthMedium")
    }
  ];

  const magicLabel = creationProgress
    ? getMagicLabel(creationProgress.percent, t)
    : null;

  return (
    <div className="space-y-6" dir={isRTL ? "rtl" : "ltr"}>
      {/* Header */}
      <div className="text-center mb-2">
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-2">
            {t("wizard.save.title")}
          </h2>
        </motion.div>
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.15 }}
        >
          <p className="text-gray-500 dark:text-gray-400 text-base">
            {t("wizard.save.subtitle")}
          </p>
        </motion.div>
      </div>

      {/* Summary — visual cards grid */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="grid grid-cols-1 sm:grid-cols-2 gap-3"
      >
        {summaryItems.map((item, index) => {
          const Icon = SUMMARY_ICONS[item.key] || CheckCircle2;
          const grad = SUMMARY_GRADIENTS[item.key] || "from-purple-400 to-indigo-500";
          return (
            <motion.div
              key={item.key}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.05 + index * 0.06 }}
              className="flex items-start gap-3 p-4 bg-white dark:bg-gray-800/60 rounded-2xl border border-gray-100 dark:border-gray-700/50 shadow-sm"
            >
              <div className={`w-9 h-9 rounded-xl bg-gradient-to-br ${grad} flex items-center justify-center flex-shrink-0 shadow-sm`}>
                <Icon className="h-4 w-4 text-white" aria-hidden="true" />
              </div>
              <div className="min-w-0">
                <p className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-0.5">
                  {item.label}
                </p>
                <p className="text-sm font-bold text-gray-900 dark:text-white truncate">
                  {item.value}
                </p>
              </div>
            </motion.div>
          );
        })}
      </motion.div>

      {/* Create Book CTA */}
      <motion.div
        whileHover={!isCreating ? { scale: 1.02 } : {}}
        whileTap={!isCreating ? { scale: 0.98 } : {}}
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.35 }}
        className="relative overflow-hidden rounded-2xl"
      >
        <Button
          onClick={onCreateBook}
          disabled={isCreating}
          className="w-full h-16 text-lg font-bold bg-gradient-to-r from-purple-600 via-indigo-600 to-violet-600 hover:from-purple-700 hover:via-indigo-700 hover:to-violet-700 gap-3 shadow-xl shadow-purple-300/40 rounded-2xl border-0"
          aria-label={t("wizard.nav.createBook")}
        >
          {/* Shimmer */}
          {!isCreating && (
            <motion.div
              className="absolute inset-0 bg-white/15 skew-x-12 pointer-events-none"
              animate={{ x: ["-200%", "300%"] }}
              transition={{ duration: 2, repeat: Infinity, repeatDelay: 1.5, ease: "easeInOut" }}
              aria-hidden="true"
            />
          )}
          {isCreating ? (
            <Loader2 className="h-6 w-6 animate-spin relative z-10" aria-hidden="true" />
          ) : (
            <Sparkles className="h-6 w-6 relative z-10" aria-hidden="true" />
          )}
          <span className="relative z-10">
            {isCreating
              ? t("wizard.nav.generating")
              : t("wizard.nav.createBook")
            }
          </span>
        </Button>
      </motion.div>

      {/* Generation Progress */}
      {isCreating && creationProgress && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="border-purple-200 dark:border-purple-800/50 shadow-sm overflow-hidden">
            <CardContent className="p-5 space-y-4">
              {/* Magical label */}
              <motion.div
                key={magicLabel}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3 }}
                aria-live="polite"
              >
                <p className="text-center text-base font-bold text-purple-700 dark:text-purple-300">
                  {magicLabel}
                </p>
              </motion.div>

              {/* Progress bar */}
              <div className="space-y-1.5">
                <div className="w-full bg-gray-100 dark:bg-gray-800 rounded-full h-3 overflow-hidden">
                  <motion.div
                    className="bg-gradient-to-r from-purple-500 via-fuchsia-500 to-indigo-500 h-3 rounded-full"
                    initial={{ width: 0 }}
                    animate={{ width: `${creationProgress.percent}%` }}
                    transition={{ duration: 0.5, ease: "easeOut" }}
                  />
                </div>
                <div className="flex justify-end">
                  <motion.div
                    key={creationProgress.percent}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="text-xs font-bold text-purple-600 dark:text-purple-400"
                  >
                    {creationProgress.percent}%
                  </motion.div>
                </div>
              </div>

              {/* Step indicator */}
              {creationProgress.step && (
                <p className="text-xs text-gray-400 dark:text-gray-500 text-center">
                  {creationProgress.step}
                </p>
              )}
            </CardContent>
          </Card>
        </motion.div>
      )}
    </div>
  );
}
